# Generated by Django 3.1.4 on 2020-12-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201220_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.svg', upload_to='profile-pics'),
        ),
    ]
